### ISSUE TITLE
No eligible torsions found during geometry engine proposal

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#182]
We're still running into some `no eligible torsions` errors during the geometry proposal, even for the [`ValenceSmallMoleculeLibraryTestSystem`](https://travis-ci.org/choderalab/perses/jobs/118606638):
```
======================================================================
ERROR: Testing SAMS sampler with ValenceSmallMoleculeLibraryTestSystem 'vacuum'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 965, in run
    self.update()
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 949, in update
    self.update_sampler()
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 917, in update_sampler
    self.sampler.update()
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 794, in update
    self.update_state()
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 723, in update_state
    geometry_new_positions, geometry_logp_propose = self.geometry_engine.propose(topology_proposal, geometry_old_positions, self.sampler.thermodynamic_state.beta)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 109, in propose
    logp_proposal, new_positions = self._logp_propose(top_proposal, current_positions, beta, direction='forward')
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 193, in _logp_propose
    atom_proposal_order, logp_choice = proposal_order_tool.determine_proposal_order(direction='forward')
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 1150, in determine_proposal_order
    chosen_torsion, logp_choice = self._choose_torsion(atoms_with_positions, atom)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 1197, in _choose_torsion
    raise Exception("No eligible torsions found for placing atom %s." % str(atom_for_proposal))
Exception: No eligible torsions found for placing atom <Atom C2 [3]; In MOL 0>.
```

**Comment by jchodera** [comment]
I'm actually seeing lots of these in the `ValenceSmallMoleculeLibraryTestSystem`:
https://travis-ci.org/choderalab/perses/jobs/118609137#L942-L1096

Maybe we can prioritize fixing this?  Having the code crap out in the middle of a run isn't going to be very good for testing.

**Comment by pgrinaway** [comment]
Fixed in #186

**Comment by jchodera** [comment]
I think this is back. In the [Jenkins tests](https://jenkins.choderalab.org/job/test-perses-linux-xeon-gtxtitan-src/28/console), I see this error:
```
======================================================================
ERROR: Try proposing geometries for all T4 ligands from all T4 ligands
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/tests/test_geometry_engine.py", line 219, in test_propose_lysozyme_ligands
    run_proposals(proposals)
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/tests/test_geometry_engine.py", line 250, in run_proposals
    new_positions, logp = geometry_engine.propose(top_proposal, current_positions, beta)
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 110, in propose
    logp_proposal, new_positions = self._logp_propose(top_proposal, current_positions, beta, direction='forward')
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 194, in _logp_propose
    atom_proposal_order, logp_choice = proposal_order_tool.determine_proposal_order(direction='forward')
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 1187, in determine_proposal_order
    chosen_torsion, logp_choice = self._choose_torsion(atoms_with_positions, atom)
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 1234, in _choose_torsion
    raise NoTorsionError("No eligible torsions found for placing atom %s." % str(atom_for_proposal))
NoTorsionError: No eligible torsions found for placing atom <Atom C1 [0]; In MOL_0 0>.
```
This could just be a test case that hasn't been updated yet.

**Comment by jchodera** [comment]
I'm still seeing this in [`T4LysozymeInhibitorsTestSystem`](https://github.com/choderalab/perses/pull/221#issuecomment-230110358), so @pgrinaway will likely need to fix this for the paper.

**Comment by pgrinaway** [comment]
I haven't seen this error in a very long time...has anyone else? This is related to #189 which is up soon on my docket, but once the test suite for `GeometryEngine` is finished, I will close this.

**Comment by jchodera** [comment]
I think the Jenkins tests were still failing with this error, but we
haven't been able to run them in some time.

You can close and we can reopen if we notice them again.
