### ISSUE TITLE
Package error?

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#314]
Not sure what is going on [here](https://travis-ci.org/choderalab/perses/jobs/192007012#L495), but I'll take a look tomorrow.

**Comment by jchodera** [comment]
It appears to say [we need to rebuild `ambertools16`](https://travis-ci.org/choderalab/perses/jobs/192007012#L466-L468):
```
ERROR conda.core.link:_execute_actions(317): An error occurred while installing package 'omnia::ambermini-16.16.0-6'.
PaddingError: Placeholder of length '80' too short in package /home/travis/miniconda/conda-bld/conda-recipe_1484435295421/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/acdoctor.
The package must be rebuilt with conda-build > 2.0.
```

**Comment by Lnaden** [comment]
This should have been fixed by omnia-md/conda-recipes#674

**Comment by pgrinaway** [comment]
Hm, looks like it's [still failing](https://travis-ci.org/choderalab/perses/jobs/192845880#L496)?

**Comment by jchodera** [comment]
The actual issue is an [anaconda NetCDF/HDF5 library issue](https://travis-ci.org/choderalab/perses/jobs/192845880#L767-L794).

See [here](https://github.com/openpathsampling/openpathsampling/pull/655#issuecomment-272853914).

The solution is to [temporarily pin numpy to 1.10](https://github.com/openpathsampling/openpathsampling/pull/655/files).

**Comment by Lnaden** [comment]
I was going to say, I didnt think that was an omnia error. That said, we did not test every omnia package, so there may be some dependencies which fail.

**Comment by pgrinaway** [comment]
Should be resolved in #317
